import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import Footer from "@/components/layout/Footer/Footer";
import { NextIntlClientProvider } from "next-intl";
import "@/styles/globals.scss";
import Loading from "@/components/Loading/Loading";

const montserrat = Montserrat({
	variable: "--montserrat-font",
	weight: ["400", "500"],
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function LocaleLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

	return (
		<html lang={locale} className={montserrat.variable}>
			<body>
				<Loading />
				<NextIntlClientProvider locale={locale}>
					<div className="wrapper" style={{ display: "none" }}>
						{/* <Header /> */}
						{children}
						<Footer />
					</div>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
